[project]
name = 'Digital-Identity-Verification-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.identity-contract]
path = 'contracts/identity-contract.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
